import paramiko, time, sys
t0 = time.time()
key = paramiko.Ed25519Key.from_private_key_file("/home/z/.ssh/id_ed25519")
print(f"key loaded {time.time()-t0:.1f}s", flush=True)
c = paramiko.SSHClient()
c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
t0 = time.time()
c.connect("github.com", port=22, username="git", pkey=key, look_for_keys=False, allow_agent=False, timeout=20, banner_timeout=20, auth_timeout=20)
print(f"connected+auth {time.time()-t0:.1f}s", flush=True)
t0 = time.time()
stdin, stdout, stderr = c.exec_command("git-upload-pack 'indrajith11/AgentPay.git'", timeout=25)
head = stdout.readline()
print(f"exec done {time.time()-t0:.1f}s first line: {head[:80]!r}", flush=True)
c.close()
